version: 3.0.{build}
branches: 
  only:
    - main
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2204
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
after_test:
  - dotnet tool restore && dotnet stryker --reporter dots --reporter cleartext
test_script:
  - dotnet test -s test.runsettings
for:
  - branches:
      only:
        - main
    environment:
      CODECOV_TOKEN: 82855860-51e6-44b7-a0e4-75f725a6a7be
      STRYKER_DASHBOARD_API_KEY:
        secure: zNvmKO5DpbfDRV+WFnyaetwbAexTXGi4rMSwJH9NnTtOS3SDAUjD8CIVGRsReMRf
    after_test:
      - curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -f **/*.cobertura.xml
      - dotnet tool restore && dotnet stryker --reporter dots --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY
    deploy:
      - provider: NuGet
        api_key:
          secure: 94EO1bi0K9yuzwbqFNbnIukk+xG+TJ5z5pvNc5A7zKhhArYUNpvg39Fb/tl808/N

