version: 2.2.{build}
branches: 
  only:
    - main
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
build_script:
  - dotnet build -c Release
before_test:
  - pwsh: az login --service-principal --tenant 3d4d17ea-1ae4-4705-947e-51369c5a5f79 -u 84708c19-29bc-4fb2-aa5c-bda04d55c4e9 -p $env:SPN_TOKEN
after_test:
  - dotnet tool restore && dotnet stryker -f stryker-config.yaml --reporter dots --reporter cleartext --since:main -c 4
test_script:
  - dotnet test -s test.runsettings
environment:
  SPN_TOKEN:
    secure: oVYrJIQj+NpNgiX9jS4ynUZp7U7FZIj26zy5B8PcbjOhpkGPsJceEIeJewUdcAHY
for:
  - branches:
      only:
        - main
        - stryker
    environment:
      CODECOV_TOKEN: 82855860-51e6-44b7-a0e4-75f725a6a7be
      STRYKER_DASHBOARD_API_KEY:
        secure: zNvmKO5DpbfDRV+WFnyaetwbAexTXGi4rMSwJH9NnTtOS3SDAUjD8CIVGRsReMRf
    after_test:
      - pwsh: Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe && ./codecov.exe -t $env:CODECOV_TOKEN -f **/*.cobertura.xml
      - pwsh: dotnet tool restore && dotnet stryker -f stryker-config.yaml --reporter dots --reporter dashboard --dashboard-api-key $env:STRYKER_DASHBOARD_API_KEY -c 4
    deploy:
      - provider: NuGet
        api_key:
          secure: pZYKB9EWhp9ykhnd75dMBbnc96Ti/F3pWYyRVj/toW7HDNBCl2zd7Fnw+/JNDtyV
        on:
          branch: main
