version: 2.2.{build}
branches: 
  only:
    - main
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2204
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
before_build:
  - |+
    declare repo_version=$(if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi)
    wget https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    sudo apt update
    sudo apt install dotnet-sdk-8.0 -y
build_script:
  - dotnet build -c Release
before_test:
  - az login --service-principal --tenant 3d4d17ea-1ae4-4705-947e-51369c5a5f79 -u 84708c19-29bc-4fb2-aa5c-bda04d55c4e9 -p $SPN_TOKEN
after_test:
  - dotnet tool restore && dotnet stryker --reporter dots --reporter cleartext
test_script:
  - dotnet test -s test.runsettings
environment:
  SPN_TOKEN:
    secure: oVYrJIQj+NpNgiX9jS4ynUZp7U7FZIj26zy5B8PcbjOhpkGPsJceEIeJewUdcAHY
for:
  - branches:
      only:
        - main
    environment:
      CODECOV_TOKEN: 82855860-51e6-44b7-a0e4-75f725a6a7be
      STRYKER_DASHBOARD_API_KEY:
        secure: zNvmKO5DpbfDRV+WFnyaetwbAexTXGi4rMSwJH9NnTtOS3SDAUjD8CIVGRsReMRf
    after_test:
      - curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -f **/*.cobertura.xml
      - dotnet tool restore && dotnet stryker --reporter dots --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY
    deploy:
      - provider: NuGet
        api_key:
          secure: pZYKB9EWhp9ykhnd75dMBbnc96Ti/F3pWYyRVj/toW7HDNBCl2zd7Fnw+/JNDtyV
        on:
          branch: main
